project:
  type: website
  output-dir: docs

website:
  reader-mode: false
  back-to-top-navigation: false
  title: "[***Gabriel AMMOUR***]{.main}"
  page-footer:
    foreground: "#CB410B"
    border: true
    right: "[***© 2026 Gabriel AMMOUR***]{.left-foot}"
    # right:
    
    #   - text: "Qui suis-je ?"
    #     file: about.qmd
    
    #   - text: "Mon blog"
    #     file: index.qmd
    
    #   - text: "Curiculum Vitae"
    #     file: cv.qmd

  search: false 
  
  navbar:

    foreground: "#b51818"
        
    right: 
    
      - text: "qui suis-je ?"
        file: about.qmd  
        
      - text: "mon blog"
        file: index.qmd
    
      - text: "curiculum vitae"
        file: cv.qmd
    
format:
  html:
    theme: custom.scss
    mainfont: IBM Plex Serif  
    grid: 
      sidebar-width: 200px # Gauche
      body-width: 800px # Centre
      margin-width: 200px # Droite
      gutter-width: 2rem
    smooth-scroll: true
    
editor: visual

