project:
  type: website
  output-dir: docs

website:
  google-analytics: "G-6RB86XNH1F"
  reader-mode: false
  page-footer:
    background: "#FFFFF6"
    left: "Copyright 2023, Gabriel Ammour"
    center:
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/gabriel-ammour-7263291b8
  title: "**Gabriel Ammour**"
  navbar:
    foreground: "#191970"
    background: "#FEF9E7"
    left: 
      - text: "About me"
        file: about.qmd
      - text: "Curriculum Vitae"
        file: cv.qmd
      - text: "My blog"
        file: index.qmd 
      - text: Reach me
        file: contact.qmd
    right:
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/gabriel-ammour-7263291b8

  sidebar:
    foreground: "#191970"
    background: "#FFFFF6"
    style: "floating"
    search: true
    contents:
      - section: "About me"
        contents:
        - about.qmd
        - cv.qmd
        - contact.qmd
      - section: "Blog"
        contents:
        - index.qmd
format:
  html:
    smooth-scroll: true
    theme: literia
    mainfont: helvetica
    fontcolor: "#191970"
    linkcolor: "#663399"
    backgroundcolor: "#FFFFF6"
    monofont: helvetica
    css: styles.css
    license: CC BY-SA
   

editor: visual