project:
  type: website
  output-dir: docs

website:
  reader-mode: false
  back-to-top-navigation: false
  page-footer:
    foreground: "#CB410B"
    border: true
    left: "[**{{< animate fadeInLeftBig  `© 2025 Gabriel AMMOUR` repeat=1 duration=3s >}}**]{.left-foot}"
    center: "[{{< animate pulse `Linkedin` repeat=infinite duration=2s >}}](https://www.linkedin.com/in/gabriel-ammour-7263291b8)  [{{< animate pulse `Github` repeat=infinite duration=2s >}}](https://github.com/gabammour)  [{{< animate pulse `Strava` repeat=infinite duration=2s >}}](https://www.strava.com/athletes/115618824){.left-foot}"
    right: "[**{{< animate fadeInRightBig `Made with Quarto` repeat=1 duration=3s >}}**]{.left-foot}"
  title: "[**{{< animate bounceInDown `Hello World, here's Gabriel AMMOUR` repeat=1 duration=3s >}}**]{.main}"
  
  search: false 
  
  navbar:

    foreground: "#b51818"
    
    right:
      - text: "**{{< animate fadeInRightBig `Blog` repeat=1 duration=3s >}}**"
        file: index.qmd
     
      - text: "**{{< animate fadeInRightBig `Curiculum Vitae` repeat=1 duration=3s >}}**"
        file: cv.qmd
    
      - text: "**{{< animate fadeInRightBig `Contact` repeat=1 duration=3s >}}**"
        file: contact.qmd

format:
  html:
    theme: custom.scss
    mainfont: Newsreader 
    grid: 
      sidebar-width: 0px # Gauche
      body-width: 500px # Centre
      margin-width: 0px # Droite
      gutter-width: 2rem
    smooth-scroll: true
    
editor: visual

