project:
  type: website

website:
  reader-mode: true
  page-footer:
    left: "Copyright 2023, Gabriel Ammour"
    center:
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/gabriel-ammour-7263291b8
  title: "**Gabriel Ammour**"
  navbar:
    foreground: "#191970"
    background: light
    right:
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/gabriel-ammour-7263291b8

  sidebar:
    foreground: "#191970"
    style: "floating"
    search: true
    contents:
      - section: "About me"
        contents:
        - about.qmd
        - cv.qmd
      - section: "Blog"
        contents:
        - index.qmd
format:
  html:
    theme: literia
    mainfont: helvetica
    fontcolor: "#191970"
    linkcolor: "#663399"
    monofont: helvetica
    css: styles.css

editor: visual