project:
  type: website
  output-dir: docs

website:
  reader-mode: false
  back-to-top-navigation: true
  page-footer:
    foreground: "#CB410B"
    border: true
    left: "[**© 2024 Gabriel Ammour**]{.left-foot}"
    center: "[**Made with <3 and Quarto**]{.left-foot}"
    right: 
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/gabriel-ammour-7263291b8
      - icon: strava
        href: https://www.strava.com/athletes/ammour_gabriel
  title: "[**Gabriel AMMOUR**]{.main}"
  
  search: false 
    
  navbar:

    foreground: "#b51818"
    
    right:
      - text: "Blog"
        file: index.qmd
     
      - text: "Curiculum Vitae"
        file: cv.qmd
    
      - text: "Contact"
        file: contact.qmd

format:
  html:
    theme: custom.scss
    mainfont: Newsreader 
    grid: 
      sidebar-width: 500px
      body-width: 1500px
      margin-width: 500px
      gutter-width: 3rem
    smooth-scroll: true
    
editor: visual