project:
  type: website
  output-dir: docs

website:
  reader-mode: false
  back-to-top-navigation: true
  page-footer:
    background: "#FFFFFF"
    foreground: "#FA7B0B"
    border: true
    left: "Copyright 2023, Gabriel Ammour"
    right:
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/gabriel-ammour-7263291b8
      - icon: strava
        href: https://www.strava.com/athletes/ammour_gabriel
  title: "[**Gabriel Ammour**]{.main}"
  
  navbar:
    foreground: "#FA7B0B"
    background: "#FFFFFF"
    right:
    - text: "Blog"
      file: index.qmd
    - cv.qmd
    - contact.qmd
    - icon: github
      href: https://github.com/
    - icon: linkedin
      href: https://www.linkedin.com/in/gabriel-ammour-7263291b8
    - icon: strava
      href: https://www.strava.com/athletes/ammour_gabriel
  
  sidebar:
    style: "docked"
    border: true 
    
format:
  html:
    mainfont: sans-serif
    grid: 
      sidebar-width: 500px
      body-width: 1500px
      margin-width: 500px
      gutter-width: 3rem
    smooth-scroll: true
    theme: 
      light: custom.scss
      dark: [custom.scss, dark-custom.scss]
      
editor: visual