project:
  type: website
  output-dir: docs

website:
  reader-mode: false
  back-to-top-navigation: false
  page-footer:
    foreground: "#CB410B"
    border: true
    left: "[**© 2025 Gabriel AMMOUR**]{.left-foot}"
    center: "[*Linkedin*](https://www.linkedin.com/in/gabriel-ammour-7263291b8) - [*Github*](https://github.com/gabammour) - [Strava](https://www.strava.com/athletes/115618824){.left-foot}"
    right: "[**Made with <3 and Quarto**]{.left-foot}"
  title: "[**Gabriel AMMOUR**]{.main}"
  
  search: false 
    
  navbar:

    foreground: "#b51818"
    
    right:
      - text: "Blog"
        file: index.qmd
     
      - text: "Curiculum Vitae"
        file: cv.qmd
    
      - text: "Contact"
        file: contact.qmd

format:
  html:
    theme: custom.scss
    mainfont: Newsreader 
    grid: 
      sidebar-width: 0px # Gauche
      body-width: 500px # Centre
      margin-width: 0px # Droite
      gutter-width: 2rem
    smooth-scroll: true
    
editor: visual