---
    title: "Studying meat consumption among college students"
    author: "Gabriel Ammour, [Théo Bouedo](https://lovely-dolphin-e68198.netlify.app/my_work.html), [Noa Le Roux](https://noalrx.github.io/portfolio/)"
    date: "2023-02-04"
    categories: [School projects]
    description: "🥩"
    format: 
      html: 
        toc: true
---

# Introduction

Meat consumption has become a widely debated topic in recent years, with increasing concerns over the environmental, health, and animal welfare impacts of the meat industry. In this report, we set out to examine the drivers of the weekly meat consumption among students at the University of Nantes and to explore their perceptions of these negative externalities.

# Methods

To achieve this, we conducted an online survey to evaluate the students' positions on these three causes. The results of the survey allowed us to segment the population into four types of consumers: inactive, occasional, regular, and dependent. Using multiple component analysis and clustering techniques, we were then able to determine three distinct clusters: the committed, the aware, and the skeptical. We used the ordinary least squares method to quantify and measure the magnitude of these relationships, though we caution that our results may be affected by an endogeneity problem. Despite these limitations, our findings suggest that food and health behaviors, as well as environmental concerns, have a significant impact on meat consumption among students at the University of Nantes.

# Results

Our findings indicated that the majority of the student population was aware of the negative impacts of the meat industry on the environment, health, and animal welfare. However, we observed a clear relationship between the students' cluster membership and their meat consumption patterns. Students who were skeptical about environmental, health, and animal considerations tended to be regular or dependent meat consumers, while those who were committed to food and health behaviors and environmental concerns consumed on average almost half as much meat as the aware students.

# Conclusion

In conclusion, our report highlights the need for public policies to be more specific in addressing the hazards of meat consumption, particularly processed meat, on the health of all citizens. Given that the student population seems to be relatively well-informed about animal and environmental issues, there may be an opportunity to better educate them about the health effects of meat consumption and encourage more sustainable dietary habits. As the world faces the challenges of a rapidly growing population and limited resources, reducing our dependence on meat will likely be necessary for a sustainable and healthy future.

Full text pdf [here](Ammour%20Gabriel,%20Bouedo%20Theo,%20Le%20roux%20Noa.pdf)
